In [82]:
import pandas as pd

In [83]:
df = pd.read_csv(r"E:\Neeraj\Python\customer_shopping_behavior\customer_shopping_behavior.csv")

In [ ]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
df.rename(columns={"purchase_amount_(usd)": "purchase_amount"}, inplace=True)

In [ ]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [85]:
df.shape

(3900, 18)

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [115]:
df['review_rating'].isna().sum()

0

In [ ]:
df.loc[df['review_rating'].isna(),'customer_id']

38        39
50        51
80        81
96        97
262      263
330      331
356      357
383      384
419      420
442      443
452      453
460      461
491      492
512      513
560      561
628      629
799      800
829      830
861      862
888      889
1072    1073
1109    1110
1124    1125
1134    1135
1151    1152
1176    1177
1189    1190
1208    1209
1220    1221
1230    1231
1247    1248
1292    1293
1313    1314
1326    1327
1334    1335
1341    1342
1370    1371
Name: Customer ID, dtype: int64

In [89]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='object')

In [ ]:
df['age'].unique()

array([55, 19, 50, 21, 45, 46, 63, 27, 26, 57, 53, 30, 61, 65, 64, 25, 52,
       66, 31, 56, 18, 38, 54, 33, 36, 35, 29, 70, 69, 67, 20, 39, 42, 68,
       49, 59, 47, 40, 41, 48, 22, 24, 44, 37, 58, 32, 62, 51, 28, 43, 34,
       23, 60], dtype=int64)

In [91]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [ ]:
df['location'].nunique()

50

In [93]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [ ]:
df['review_rating'].describe()

count    3863.000000
mean        3.750065
std         0.716983
min         2.500000
25%         3.100000
50%         3.800000
75%         4.400000
max         5.000000
Name: Review Rating, dtype: float64

In [ ]:
df['review_rating'].unique()

array([3.1, 3.5, 2.7, 2.9, 3.2, 2.6, 4.8, 4.1, 4.9, 4.5, 4.7, 2.8, 4.6,
       3.3, 4.4, 3.6, 5. , 4. , nan, 4.2, 3.7, 3.9, 3. , 3.8, 3.4, 4.3,
       2.5])

In [ ]:
df['review_rating'] = df['review_rating'].fillna(df.groupby('category')['review_rating'].transform('median'))

In [98]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [99]:
labels = ['Young_Adult','Adult','Middle-aged','Senior']

df['age_group'] = pd.qcut(df['age'],q=4,labels=labels)

In [100]:
df['age_group'].value_counts()

age_group
Young_Adult    1028
Middle-aged     986
Senior          944
Adult           942
Name: count, dtype: int64

In [101]:
df['frequency_of_purchases'].value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [102]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 Months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [103]:
df[['purchase_frequency_days','frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                          14            Fortnightly
1                          14            Fortnightly
2                           7                 Weekly
3                           7                 Weekly
4                         365               Annually
...                       ...                    ...
3895                        7                 Weekly
3896                       14              Bi-Weekly
3897                       90              Quarterly
3898                        7                 Weekly
3899                       90              Quarterly

[3900 rows x 2 columns]

In [104]:
(df['discount_applied'] == df['promo_code_used']).all()

True

In [105]:
df.drop(['promo_code_used'],axis = 1,inplace=True)

In [106]:
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle-aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young_Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle-aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young_Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle-aged,365
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,14,Venmo,Weekly,Middle-aged,7
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,49,Cash,Quarterly,Senior,90
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,19,Credit Card,Weekly,Young_Adult,7
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,8,Venmo,Annually,Young_Adult,365
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,4,Cash,Quarterly,Middle-aged,90

In [107]:
pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in C:\Users\Naveen Rawat\AppData\Roaming\Python\Python312\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in C:\Users\Naveen Rawat\AppData\Roaming\Python\Python312\site-packages (2.0.35)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Naveen Rawat\AppData\Roaming\Python\Python312\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: greenlet!=0.4.17 in C:\Users\Naveen Rawat\AppData\Roaming\Python\Python312\site-packages (from sqlalchemy) (3.1.1)
Note: you may need to restart the kernel to use updated packages.

WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Naveen Rawat\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\Naveen Rawat\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Naveen Rawat\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\Naveen Rawat\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ensorflow-intel (C:\Users\Naveen Rawat\AppData\Roaming\Python\Python312\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\Naveen Rawat\AppData\Roaming\Python\Python312\site-packages)

In [108]:
from urllib.parse import quote_plus
from sqlalchemy import create_engine

username = "root"
password = quote_plus("Root@123")
host = "localhost"
port = 3306
database = "customer_behavior"


engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}"
)

table_name = "customer"
df.to_sql(table_name,engine,if_exists='replace',index=False)

print("Successfully Loaded",table_name)

Successfully Loaded customer

In [ ]:
pip install pymysql sqlalchemy

from sqlalchemy import create_engine
from urllib.parse import quote_plus
'''
database - name of the database
user_name = mysql user_name
host = host of the server generally localhost
port = generally  3306
password = that you created when installed for the first time'''

engine = create_engine(you can ask chatgpt for the format of the path)
'''
table_name = "customer" -- Same table name willbe use in the mysql
df(or whatever your dataframe where the data is stored)
.to_sql(table_name,engine,if_exists = 'replace',index = False )
'''